// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars

import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAaNXzlIaKWzvR7w9688Zjnawm7fvr4_h0',
    appId: '1:520560089620:android:6b99e2e96fd93f916aa501',
    messagingSenderId: '520560089620',
    projectId: 'farmigo-704ca',
    storageBucket: 'farmigo-704ca.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAaNXzlIaKWzvR7w9688Zjnawm7fvr4_h0',
    appId: '1:520560089620:ios:6b99e2e96fd93f916aa501',
    messagingSenderId: '520560089620',
    projectId: 'farmigo-704ca',
    storageBucket: 'farmigo-704ca.firebasestorage.app',
  );
}
